using System.Collections.Generic;
using UnityEngine;

namespace DinoNet
{
    /// <summary>
    /// Plays the game's sound effects by name. Clips live in Resources/DinoAudio (generated by the
    /// DinoNet/Generate Audio editor tool), so they are always included in a headset build.
    /// A missing clip is silently ignored - sound never breaks a level.
    /// </summary>
    public static class Sfx
    {
        static readonly Dictionary<string, AudioClip> s_Cache = new Dictionary<string, AudioClip>();
        static AudioSource s_Source2D;

        public static AudioClip Get(string name)
        {
            if (string.IsNullOrEmpty(name))
                return null;

            if (s_Cache.TryGetValue(name, out var clip) && clip != null)
                return clip;

            clip = Resources.Load<AudioClip>("DinoAudio/" + name);
            s_Cache[name] = clip;
            return clip;
        }

        /// <summary>Plays a clip at full stereo, e.g. for interface sounds.</summary>
        public static void Play2D(string name, float volume = 1f, float pitch = 1f)
        {
            var clip = Get(name);
            if (clip == null)
                return;

            if (s_Source2D == null)
            {
                var host = new GameObject("Sfx 2D");
                Object.DontDestroyOnLoad(host);
                s_Source2D = host.AddComponent<AudioSource>();
                s_Source2D.spatialBlend = 0f;
                s_Source2D.playOnAwake = false;
            }

            s_Source2D.pitch = pitch;
            s_Source2D.PlayOneShot(clip, volume);
        }

        /// <summary>Plays a clip positioned in the world (3D), e.g. a dinosaur's grunt.</summary>
        public static void PlayAt(string name, Vector3 position, float volume = 1f, float pitch = 1f, float maxDistance = 25f)
        {
            var clip = Get(name);
            if (clip == null)
                return;

            var go = new GameObject("Sfx " + name);
            go.transform.position = position;
            var source = go.AddComponent<AudioSource>();
            source.clip = clip;
            source.spatialBlend = 1f;
            source.minDistance = 2f;
            source.maxDistance = maxDistance;
            source.rolloffMode = AudioRolloffMode.Linear;
            source.volume = volume;
            source.pitch = pitch;
            source.Play();
            Object.Destroy(go, clip.length / Mathf.Max(0.1f, pitch) + 0.2f);
        }
    }
}
